# Generated by Django 4.2.21 on 2025-07-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('toshkent', 'Toshkent'), ('samarqand', 'Samarqand'), ('buxoro', 'Buxoro'), ('fargona', "Farg'ona"), ('andijon', 'Andijon'), ('namangan', 'Namangan'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('xorazm', 'Xorazm'), ('jizzax', 'Jizzax'), ('navoiy', 'Navoiy'), ('sirdaryo', 'Sirdaryo'), ("qoraqalpog'iston", "Qoraqalpog'iston")], default='toshkent', max_length=255),
        ),
    ]
