# Generated by Django 5.2.4 on 2026-01-27 18:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("diagnosis", "0004_planttype_aimodel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(max_length=100, verbose_name="Nomi (O'zbek)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nomi (English)"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nomi (Русский)"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL slug")),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Masalan: fa-seedling",
                        max_length=50,
                        verbose_name="Icon (FontAwesome)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop/categories/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Tartib"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mahsulot kategoriyasi",
                "verbose_name_plural": "Mahsulot kategoriyalari",
                "ordering": ["display_order", "name_uz"],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_cart",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savatcha",
                "verbose_name_plural": "Savatchalar",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Buyurtma raqami"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="To'liq ism"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Manzil")),
                ("city", models.CharField(max_length=100, verbose_name="Shahar")),
                ("region", models.CharField(max_length=100, verbose_name="Viloyat")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Pochta indeksi"
                    ),
                ),
                (
                    "delivery_notes",
                    models.TextField(
                        blank=True, verbose_name="Yetkazib berish haqida izoh"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Naqd pul (yetkazib berishda)"),
                            ("card", "Karta orqali"),
                            ("payme", "Payme"),
                            ("click", "Click"),
                        ],
                        max_length=20,
                        verbose_name="To'lov usuli",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Jami (mahsulotlar)",
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Yetkazib berish narxi",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Chegirma",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Jami to'lov"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("confirmed", "Tasdiqlandi"),
                            ("processing", "Tayyorlanmoqda"),
                            ("shipped", "Jo'natildi"),
                            ("delivered", "Yetkazildi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="To'langan"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tasdiqlangan vaqt"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yetkazilgan vaqt"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma",
                "verbose_name_plural": "Buyurtmalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Mahsulot nomi"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL slug")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Qisqa tavsif"
                    ),
                ),
                ("description", models.TextField(verbose_name="To'liq tavsif")),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="shop/products/", verbose_name="Asosiy rasm"
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop/products/",
                        verbose_name="Qo'shimcha rasm 2",
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop/products/",
                        verbose_name="Qo'shimcha rasm 3",
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop/products/",
                        verbose_name="Qo'shimcha rasm 4",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Narx (so'm)",
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Asl narx (chegirma uchun)",
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ombordagi miqdor",
                    ),
                ),
                (
                    "min_order_quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Minimal buyurtma",
                    ),
                ),
                (
                    "max_order_quantity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Maksimal buyurtma"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Yangi ko'chat"),
                            ("growing", "O'sayotgan"),
                            ("mature", "Pishgan"),
                        ],
                        default="growing",
                        max_length=20,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        blank=True,
                        help_text="Masalan: 20-30 sm",
                        max_length=50,
                        verbose_name="Balandlik",
                    ),
                ),
                (
                    "pot_size",
                    models.CharField(
                        blank=True,
                        help_text="Masalan: 15 sm diametr",
                        max_length=50,
                        verbose_name="Idish o'lchami",
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        blank=True,
                        help_text="Masalan: 6 oy",
                        max_length=50,
                        verbose_name="Yoshi",
                    ),
                ),
                (
                    "care_level",
                    models.CharField(
                        choices=[
                            ("easy", "Oson"),
                            ("moderate", "O'rtacha"),
                            ("difficult", "Qiyin"),
                        ],
                        default="moderate",
                        max_length=20,
                        verbose_name="Parvarish qilish darajasi",
                    ),
                ),
                (
                    "light_requirement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Yorug'lik talabi"
                    ),
                ),
                (
                    "water_requirement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Suv talabi"
                    ),
                ),
                (
                    "temperature_range",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Harorat oralig'i"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Meta sarlavha"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Meta tavsif"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Meta kalit so'zlar"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Tanlangan mahsulot"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Mavjud"),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
                ),
                (
                    "sales_count",
                    models.IntegerField(default=0, verbose_name="Sotuvlar soni"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratuvchi",
                    ),
                ),
                (
                    "plant_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_products",
                        to="diagnosis.planttype",
                        verbose_name="O'simlik turi",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.productcategory",
                        verbose_name="Kategoriya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahsulot",
                "verbose_name_plural": "Mahsulotlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="Mahsulot nomi"),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Mahsulot narxi"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Miqdor",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Jami"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.order",
                        verbose_name="Buyurtma",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product",
                        verbose_name="Mahsulot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma elementi",
                "verbose_name_plural": "Buyurtma elementlari",
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Reyting",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Sarlavha"
                    ),
                ),
                ("comment", models.TextField(verbose_name="Sharh")),
                (
                    "would_recommend",
                    models.BooleanField(
                        default=True, verbose_name="Tavsiya qilasizmi?"
                    ),
                ),
                (
                    "image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop/reviews/",
                        verbose_name="Rasm 1",
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop/reviews/",
                        verbose_name="Rasm 2",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Tasdiqlangan"),
                ),
                (
                    "helpful_count",
                    models.IntegerField(default=0, verbose_name="Foydali deb topildi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tasdiqlagan",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shop.product",
                        verbose_name="Mahsulot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahsulot sharhi",
                "verbose_name_plural": "Mahsulot sharhlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="wishlisted_by",
                        to="shop.product",
                        verbose_name="Mahsulotlar",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sevimlilar",
                "verbose_name_plural": "Sevimlilar",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Miqdor",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.cart",
                        verbose_name="Savatcha",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product",
                        verbose_name="Mahsulot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savat elementi",
                "verbose_name_plural": "Savat elementlari",
                "unique_together": {("cart", "product")},
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="shop_produc_slug_76971b_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_available"],
                name="shop_produc_is_acti_b04ab0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="shop_produc_created_ddfb00_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("product", "user")},
        ),
    ]
