# Generated by Django 5.2.3 on 2025-06-18 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(blank=True)),
                ('causes', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(default='uz', max_length=10)),
                ('ai_source', models.CharField(default='GEMINI', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plant_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('ai_result', models.TextField(blank=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis.disease')),
            ],
        ),
    ]
