# Generated by Django 4.2.21 on 2025-07-25 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='disease',
            name='causes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='causes_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='causes_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='region_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='region_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='region_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantimage',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantimage',
            name='disease_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plantimage',
            name='status',
            field=models.CharField(choices=[('processing', 'Tahlil qilinmoqda'), ('completed', 'Yakunlandi'), ('failed', 'Xato')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
