# Generated by Django 5.2.4 on 2026-01-27 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagnosis", "0003_alter_plantimage_options_disease_causes_en_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Masalan: tomato, potato, corn",
                        max_length=50,
                        unique=True,
                        verbose_name="Kod",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        help_text="Masalan: Pomidor, Kartoshka",
                        max_length=100,
                        verbose_name="Nomi (O'zbek)",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nomi (English)"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nomi (Русский)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                (
                    "scientific_name",
                    models.CharField(
                        blank=True,
                        help_text="Masalan: Solanum lycopersicum",
                        max_length=150,
                        verbose_name="Ilmiy nomi",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Masalan: Sabzavot, Meva, Don",
                        max_length=50,
                        verbose_name="Kategoriya",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plant_types/",
                        verbose_name="Rasm",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
            ],
            options={
                "verbose_name": "O'simlik turi",
                "verbose_name_plural": "O'simlik turlari",
                "ordering": ["name_uz"],
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Masalan: Pomidor kasalliklari modeli v2.0",
                        max_length=255,
                        verbose_name="Model nomi",
                    ),
                ),
                (
                    "detection_type",
                    models.CharField(
                        choices=[
                            ("disease", "Kasallik aniqlash"),
                            ("pest", "Zararkunanda aniqlash"),
                        ],
                        default="disease",
                        max_length=20,
                        verbose_name="Aniqlash turi",
                    ),
                ),
                (
                    "model_file",
                    models.FileField(
                        help_text="TensorFlow/Keras .h5 model fayli",
                        upload_to="ai_models/",
                        verbose_name="Model fayli (.h5)",
                    ),
                ),
                (
                    "class_indices_file",
                    models.FileField(
                        help_text="Sinflar indekslari JSON fayli",
                        upload_to="ai_models/",
                        verbose_name="Class indices fayli (.json)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Model haqida qo'shimcha ma'lumot",
                        verbose_name="Tavsif",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Faqat faol modellar ishlatiladi",
                        verbose_name="Faol",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Model versiyasi",
                        max_length=50,
                        verbose_name="Versiya",
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True,
                        help_text="Model aniqligi (test ma'lumotlarida)",
                        null=True,
                        verbose_name="Aniqlik (%)",
                    ),
                ),
                (
                    "total_classes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sinflar soni"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yuklangan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yuklagan foydalanuvchi",
                    ),
                ),
                (
                    "plant_type",
                    models.ForeignKey(
                        help_text="Qaysi o'simlik uchun model",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_models",
                        to="diagnosis.planttype",
                        verbose_name="O'simlik turi",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Model",
                "verbose_name_plural": "AI Modellar",
                "ordering": ["-uploaded_at"],
                "unique_together": {("detection_type", "plant_type", "version")},
            },
        ),
    ]
